defaults: &defaults
  user_uuid: "66666666-2222-4444-9999-000000000000" 
  study_uuid: "55555555-2222-3333-6666-777777777777"
  cost_code: "cost code"
  input_tube_role: "samples.extraction.manual.dna_and_rna.input_tube_nap"

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
